version: '3'
services:
  strapi:
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-strapi}
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapi}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-strapi}
      DATABASE_SSL: ${DATABASE_SSL:-false}
      APP_KEYS: ${APP_KEYS:-devKey1,devKey2}
      API_TOKEN_SALT: ${API_TOKEN_SALT:-devSalt1}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET:-devSecret1}
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-strapi}
      POSTGRES_USER: ${DATABASE_USERNAME:-strapi}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-strapi}
