name: Reusable deploy workflow

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_ACCOUNT:
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.envName }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Install copilot
        run: |
            wget https://github.com/aws/copilot-cli/releases/download/v1.13.0/copilot-linux -O /usr/local/bin/copilot
            chmod +x /usr/local/bin/copilot
      - name: Deploy App
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}"
          export AWS_DEFAULT_ACCOUNT="${{ secrets.AWS_DEFAULT_ACCOUNT }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          cd deployment/copilot/
          copilot svc deploy --name app --env ${{ inputs.envName }}
