name: Deploy to PROD

on:
  push:
    branches:
      - deployment

jobs:
  deploy-prod:
    name: Deploy to Prod
    uses: bitscard/strapi/.github/workflows/deploy.yml@deployment
    with:
      envName: test
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_DEFAULT_ACCOUNT }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#  slack:
#    name: Slack
#    runs-on: ubuntu-latest
#    needs: deploy-prod
#    steps:
#      - name: Send PR notification to Slack
#        id: slack-release
#        uses: slackapi/slack-github-action@v1.18.0
#        with:
#          payload: |
#            {
#              "text": "A new release of Bits Card Website has been deployed to Production.",
#              "blocks": [
#                {
#                  "type": "section",
#                  "text": {
#                    "type": "mrkdwn",
#                    "text": "A new release of Bits Card Website has been deployed to Production."
#                  }
#                }
#              ]
#            }
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_RELEASE }}
#          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
